name: my_store
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


# ----- Packages Start ----- #

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.2

# ----- Packages End ----- #


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # ----- Local Assets Folders Start ----- #

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/img/
    - assets/logos/ 

  # ----- Local Assets Folders End ----- #  

  
  # ----- Local Fonts Start ----- #

  
  # ----- Local Fonts Ends ----- #
