name: my_store
description: "E-commerce store."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


# ----- Packages Start ----- #

dependencies:
  flutter:
    sdk: flutter
  
  # Icons Packages
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # Utility Packages
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  lottie: ^3.1.0
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # State Management Packages
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9

  # SigIn
  google_sign_in: ^6.2.1

# ----- Packages End ----- #


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # ----- Local Assets Folders Start ----- #

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/img/onboarding/
    - assets/img/illustration/
    - assets/img/banners/
    - assets/img/products/
    - assets/img/users/
    - assets/img/animations/
    - assets/logos/ 

  # ----- Local Assets Folders End ----- #  

  
  # ----- Local Fonts Start ----- #

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  
  # ----- Local Fonts Ends ----- #
